### ISSUE TITLE
Styling issue

### ISSUE THREAD

**Issue by Skribbles64** [butterknight/bandcamp-volume-control#4]
Slider syling doesn't match the styling of built in Bandcamp UI.

![image](https://user-images.githubusercontent.com/94587115/210661332-b859610b-f267-481e-a0d6-25ac94efd97d.png)
![image](https://user-images.githubusercontent.com/94587115/210661428-2eba7fba-e392-4f6a-ab79-0d98ec226f57.png)

Could you set it to follow the site's set colours? (if you can't, setting it to follow the default would be acceptable.)
And disable rounding, as Bandcamp doesn't have rounded element borders.

**Comment by butterknight** [comment]
Hi! Thanks for reporting the issue.

I will take a look at the colours issue for sure because it should pick up the colours from the existing BC elements.

I'm a bit conflicted about the roundness because I originally made it round to differentiate it from the main slider people are used to (so as not to confuse the two).

**Comment by Skribbles64** [comment]
Hi, thanks for checking it out!
